name: Laravel Deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      EB_APPLICATION_NAME_SHORT: lob
      EB_APPLICATION_NAME: laravel-on-beanstalk

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_APPLICATION_NAME_SHORT }}-master
        version_label: ${{ env.GITHUB_SHA }}
        region: ${{ env.AWS_REGION }}
        deployment_package: deploy.zip
